CSC517-Lib-Booking-System/config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :rooms
  resources :users

  root 'sessions#welcome'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'searchAllRoom', to: 'rooms#searchAllRoom'

  get 'showmine', to: 'histories#showmine'

  #get 'showother', to: 'histories#showother'

  get 'show_user_history', to: 'histories#show_user_history'

  get 'show_room_history', to: 'histories#show_room_history'

  get 'sign_up', to: 'users#sign_up'

  get 'login', to: 'sessions#new'

  post 'sign_up', to: 'users#create'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  delete 'switch', to: 'sessions#switch'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

CSC517-Lib-Booking-System/app/models/room.rb
class Room < ApplicationRecord
  validates_inclusion_of :size,:in => %w{ 4 6 12 }
  validates_inclusion_of :building,:in => %w{James.B.Hunt D.H.Hill}
  validates :number, presence: true
  validates :size, presence: true
  validates :building, presence: true
  has_many :history

  def self.search(number, size, building)
      if number != '' && size == '' && building == ''
        where("number LIKE ?", "%#{number}%")
      elsif number != '' && size == '' && building != ''
        where("number LIKE ?", "%#{number}%").where("building LIKE ?", "%#{building}%")
      elsif number != '' && size != '' && building == ''
        where("number LIKE ?", "%#{number}%").where("size LIKE ?", "%#{size}%")
      elsif number != '' && size != '' && building != ''
        where("number LIKE ?", "%#{number}%").where("size LIKE ?", "%#{size}%").where("building LIKE ?", "%#{building}%")
      elsif number == '' && size == '' && building != ''
        where("building LIKE ?", "%#{building}%")
      elsif number == '' && size != '' && building == ''
        where("size LIKE ?", "%#{size}%")
      elsif number == '' && size != '' && building != ''
        where("size LIKE ?", "%#{size}%").where("building LIKE ?", "%#{building}%")
      end
      #if building != ''
       # where("building LIKE ?", "%#{building}%")
      #end
  end

  def self.searchSize(search)
    where("size LIKE ?", "%#{search}%")
  end
end

CSC517-Lib-Booking-System/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include RoomsHelper
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :show, :index, :new, :creat, :destroy]
  before_action :admin_login, only: [:new, :create, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    if params[:searchNumber] == ''  && params[:searchSize] == '' && params[:searchBuilding] == ''
      @rooms = Room.all.order('created_at DESC')
    else
      @rooms = Room.search(params[:searchNumber], params[:searchSize], params[:searchBuilding])
    end
    #elsif params[:searchSize] != ''
      #@rooms = Room.searchSize(params[:searchSize])
    #else
    #end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    sql = "select id from rooms where building = '#{@room.building}' and number = '#{@room.number}' "
    h = Room.find_by_sql(sql)
    if !h[0].nil? # Room is already existed
      flash.now[:danger] = 'Room Already Existed'
      render "new"
    else # Room dosen't exist
      respond_to do |format|
        if @room.save
          format.html { redirect_to @room }
          format.json { render :show, status: :created, location: @room }
          flash[:success] = 'Room Was Successfully Created'
        else
          format.html { render :new }
         format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room }
        format.json { render :show, status: :ok, location: @room }
        flash[:success] = 'Room Was Successfully Updated'
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    sql = "delete from histories where number = '#{@room.number}' and building = '#{@room.building}' and (date > '#{Time.now.to_date}' or (date = '#{Time.now.to_date}' and begintime > '#{Time.now.hour}' ))"
    h = History.find_by_sql(sql)
    @room.destroy
    flash[:success] = 'Room Is Successfully Deleted'
    redirect_to rooms_path
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:number, :size, :building)
    end
end

CSC517-Lib-Booking-System/app/helpers/rooms_helper.rb
module RoomsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please Log In."
      redirect_to login_url
    end
  end

  def current_user?(user)
    user == current_user end

  def admin_login
    unless isAdmin?
      flash[:danger] = "Permission Denied! Only Admin Have Authority To Create Users."
      redirect_to(current_user)
    end
  end

end

CSC517-Lib-Booking-System/app/views/rooms/_form.html.erb
<% provide(:title, "Edit Room") %>
<div class="row">
  <div>
    <%= form_for(room) do |f| %>
        <% if room.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

              <ul>
                <% room.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :number %>
          <%= f.text_field :number %>
        </div>

        <div class="field">
          <%= f.label :size %>
          <%= select_tag("room[size]", options_for_select([['Small', "4"], ['Medium', "6"], ['Large', "12"]], 3))%>
        </div>

        <div class="field">
          <%= f.label :building %>
          <%= select_tag("room[building]", options_for_select([['James.B.Hunt', "James.B.Hunt"], ['D.H.Hill', "D.H.Hill"]], 2))%>
        </div>

        <div class="actions", id="button">
          <%= f.submit "Save Change", class: "btn btn-danger" %>
          <%= link_to 'Discard', rooms_path, class: "btn btn-primary"%>
        </div>
    <% end %>

  </div>
</div>

CSC517-Lib-Booking-System/app/views/rooms/_post.html.erb
<% if @rooms.present? %>
    <%= render @rooms %>
<% else %>
    <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>

CSC517-Lib-Booking-System/app/views/rooms/edit.html.erb
<h1>Edit Room</h1>

<%= render 'form', room: @room %>

CSC517-Lib-Booking-System/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>
<table id="room_index">
  <thead>
    <tr>
      <th style="width: 100px">Room #</th>
      <th style="width: 100px">Size</th>
      <th style="width: 200px">Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.size %></td>
        <td><%= room.building %></td>
        <td id="show"><%= link_to 'Detail', room %></td>
        <% if isAdmin? %>
            <td id="edit"><%= link_to 'Edit', edit_room_path(room) %></td>
            <td id="delete"><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td id="history"><%= link_to 'Booking History', show_room_history_path(:number => room.number, :building => room.building) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</br>
<div class="actions", id="button">
  <%= link_to 'Add Room', new_room_path, class:"btn btn-danger" if isAdmin? %>
</div>

CSC517-Lib-Booking-System/app/views/rooms/new.html.erb
<h1>New Room</h1>
<%= render 'form', room: @room %>

CSC517-Lib-Booking-System/app/views/rooms/searchAllRoom.html.erb
<% provide(:title, "Search Room") %> <h1>Search Room</h1>
<%= form_tag(rooms_path, :method => "get", id: "search-form") do %>
    <div class="field">
      <%= text_field_tag :searchNumber, params[:searchNumber], placeholder: "Search by number" %>
    </div>

    <div class="field">
      <%= select_tag :searchSize, options_for_select([['', ], ['4', "4"], ['6', "6"], ['12', "12"]], 4)%>
    </div>

    <div class="field">
      <%= select_tag :searchBuilding, options_for_select([['', ], ['James.B.Hunt', "James.B.Hunt"], ['D.H.Hill', "D.H.Hill"]], 3)%>
    </div>
    <%= submit_tag "Search", class: "btn btn-danger" %>
<% end %>

CSC517-Lib-Booking-System/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <strong>Room Number:</strong>
  <%= @room.number %>
</div>
</br>
<div>
  <strong>Size:</strong>
  <%= @room.size %>
</div>
</br>
<div>
  <strong>Building:</strong>
  <%= @room.building %>
</div>
</br>
<div>
  <strong>Add Time:</strong>
  <%= @room.created_at %>
</div>
</br>
<div class="actions", id="button">
  <%= link_to 'Back', rooms_path, class: "btn btn-danger" %>
</div>