CSC517-Lib-Booking-System/config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :rooms
  resources :users

  root 'sessions#welcome'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'searchAllRoom', to: 'rooms#searchAllRoom'

  get 'showmine', to: 'histories#showmine'

  #get 'showother', to: 'histories#showother'

  get 'show_user_history', to: 'histories#show_user_history'

  get 'show_room_history', to: 'histories#show_room_history'

  get 'sign_up', to: 'users#sign_up'

  get 'login', to: 'sessions#new'

  post 'sign_up', to: 'users#create'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  delete 'switch', to: 'sessions#switch'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

CSC517-Lib-Booking-System/app/views/layouts/_footer.html.erb
<footer>
  <nav><ul>
    <li><%= link_to "About", static_pages_about_path %></li>
    <li><%= link_to "Contact", static_pages_contact_path %></li>
  </ul></nav>
</footer>

CSC517-Lib-Booking-System/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse", id="booking_system">
  <div class="container">
  <%= link_to "NCSU Library Booking System", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
            <li style="font-weight: bold"><%= link_to "Hey there! #{current_user.name}" %></li>
            <li><%= link_to "Home", root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Room <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Rooms", rooms_path %></li>
                <li><%= link_to "Search Room", searchAllRoom_path(current_user) %></li>
                <li><%= link_to "Book Room", new_history_path %>
                <li><%= link_to "My Booking History", showmine_path %></li>
              </ul>
            </li>
            <% if isAdmin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Manage <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Manage User", users_path%></li>
                    <li><%= link_to "Manage Room", rooms_path%></li>
                    <li><%= link_to "Manage Booking History", histories_path%></li>
                  </ul>
                </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Switch User", switch_path, method: "delete" %></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %> </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
</div>
</header>

CSC517-Lib-Booking-System/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

CSC517-Lib-Booking-System/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSC517LibBookingSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>  </body>
</html>