CSC517-Lib-Booking-System/config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :rooms
  resources :users

  root 'sessions#welcome'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'searchAllRoom', to: 'rooms#searchAllRoom'

  get 'showmine', to: 'histories#showmine'

  #get 'showother', to: 'histories#showother'

  get 'show_user_history', to: 'histories#show_user_history'

  get 'show_room_history', to: 'histories#show_room_history'

  get 'sign_up', to: 'users#sign_up'

  get 'login', to: 'sessions#new'

  post 'sign_up', to: 'users#create'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  delete 'switch', to: 'sessions#switch'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

CSC517-Lib-Booking-System/app/models/user.rb
class User < ApplicationRecord
  #attr_accessor :email, :password, :name ,:authority
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, presence: true
  validates :authority, presence: true
  has_secure_password
  has_many :history

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost) end

end

CSC517-Lib-Booking-System/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :show, :index, :new, :destroy]
  before_action :correct_user_show, only: [:show]
  #user cannot see other's info, admin can
  before_action :correct_user_edit, only:[:edit, :update]
  #admin and user cannot edit other's info
  before_action :admin_login, only: [:new, :destroy, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if logged_in?
        if @user.save
          format.html { redirect_to @user }
          format.json { render :show, status: :created, location: @user }
          flash[:success] = "User Was Successfully Created."
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        if @user.save
          format.html { redirect_to login_path }
          format.json { render :login_path, status: :created }
          flash[:success] = "User Was Successfully Created."
        else
          format.html { render :sign_up }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User info was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    #unless @user.update(user_params)
      #respond_to do /format/
        #format.html { render :edit }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      #end
    #else
      #redirect_to @user
      #flash[:success] = 'User Info Was Successfully Updated.'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.authority == '2'
      flash[:danger] = 'Pre-configured Admin Cannot Be Deleted'
      redirect_to users_path
    elsif @user.email == current_user.email
      flash[:danger] = 'Oops. Don\'t Delete Yourself'
      redirect_to users_path
    else
      sql = "delete from histories where email = '#{@user.email}' and (date > '#{Time.now.to_date}' or (date = '#{Time.now.to_date}' and begintime > '#{Time.now.hour}' ))"
      h = History.find_by_sql(sql)
      @user.destroy
      redirect_to users_path
      flash[:success] = 'User Was Successfully Deleted'
    end
  end

  # show history
  def showhistory
  end

  # member sign up
  def sign_up
    @user = User.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :name, :authority)
    end
end

CSC517-Lib-Booking-System/app/helpers/users_helper.rb
module UsersHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please Log In."
      redirect_to login_url
    end
  end

  def correct_user_show
    @user = User.find(params[:id])
    unless current_user?(@user) || isAdmin?
      redirect_to(current_user)
      flash[:danger] = "Naughty! Cannot See Other's Info"
    end
    #redirect_to(root_url) unless current_user?(@user)
  end

  def correct_user_edit
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to(current_user)
      flash[:danger] = "Permission Denied! You Can't Edit Other's Info"
    end
  end

  def current_user?(user)
    user == current_user end

  def admin_login
    unless isAdmin?
      flash[:danger] = "Permission Denied! Only Admin Have Authority To Create Users."
      redirect_to(current_user)
    end
  end
  def get_current_email(user)
    return user.email
  end

end

CSC517-Lib-Booking-System/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :authority %>
    <%= select_tag("user[authority]", options_for_select([['Admin', "1"],['User', "0"]], 2)) %>
  </div>

  <div class="actions", id="button">
    <%= f.submit "Create", class: "btn btn-danger" %>
    <%= link_to 'Back', users_path, class: "btn btn-primary", data: { confirm: 'Do You Want To Discard The Change?' } %>
  </div>
<% end %>

CSC517-Lib-Booking-System/app/views/users/edit.html.erb
<% provide(:title, "Edit User") %> <h1>Update Your Profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <div class="actions", id="button">
          <%= f.submit "Save Change", class: "btn btn-danger" %>
          <%= link_to 'Discard', current_user, class: "btn btn-primary"%>
        </div>
    <% end %>

    </div>
  </div>

CSC517-Lib-Booking-System/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div>
<h1>Users</h1>

<table id="user_index">
  <thead>
    <tr>
      <th style="width: 250px">Email</th>
      <th style="width: 200px">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |f| %>
      <tr>
        <td><%= f.email %></td>
        <td><%= f.name %></td>
        <td id="show"><%= link_to 'Detail', f %></td>
        <td id="delete"><%= link_to 'Delete', f, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td id="history"><%= link_to 'Booking History', show_user_history_path(:email => f.email) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div class="actions", id="button">
    <%= link_to 'Add User', new_user_path, class:"btn btn-danger" %>
</div>

CSC517-Lib-Booking-System/app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form', user: @user %>

CSC517-Lib-Booking-System/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <strong>Email:</strong>
  <%= @user.email %>
</div>
</br>
<div>
  <strong>Name:</strong>
  <%= @user.name %>
</div>
</br>
<div>
  <strong>Type:</strong>
  <% if @user.authority == '0'%>
      User
  <% else %>
      Admin
  <% end %>
</div>
</br>
<div>
  <strong>Registration Time:</strong>
  <%= @user.created_at %>
</div>
</br>
<% if isAdmin? && @user.email != current_user.email %>
    <div class="actions", id="button">
        <%= link_to 'Back', users_path, class: "btn btn-danger" %>
    </div>
<% end %>

CSC517-Lib-Booking-System/app/views/users/showhistory.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>
<% sql = "select *from histories where email = '#{@user.email}'"
   @histories = History.find_by_sql(sql)
  %>
<table>
  <thead>
  <tr>
    <th>Number</th>
    <th>Building</th>
    <th>Email</th>
    <th>Date</th>
    <th>Begintime</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @histories.each do |history| %>
      <tr>
        <td><%= history.number %></td>
        <td><%= history.building %></td>
        <td><%= history.email %></td>
        <td><%= history.date %></td>
        <td><%= history.begintime %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

CSC517-Lib-Booking-System/app/views/users/sign_up.html.erb
<% provide(:title, "Sign Up") %>
<h1>Creat Your Account</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="field">
          <%= hidden_field_tag("user[authority]", '0') %>
        </div>

        <div class="actions", id="button">
          <%= f.submit "Create", class: "btn btn-danger" %>
          <%= link_to 'Cancel', login_path, class: "btn btn-primary"%>
        </div>
    <% end %>

  </div>
</div>